name: Multi-branch-creation
run-name: ${{ github.actor }} is executing Pipeline
on:
  workflow_dispatch:
    inputs:
      Branchname:
        description: 'Select Branch'
        required: true
        default: 'master'
        type: choice
        options:
        - master
jobs:
  Multi-Branch-Creation:
    runs-on: windows-2019
    steps:
      - name: Cloning Input File
        uses: actions/checkout@v3
      - run: |
          echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "ðŸ–¥ï¸ The Workspace ${{ github.workspace }} is now ready."
          tree /f ${{ github.workspace }}
      - name: Gettin Credentials
        shell: pwsh
        env:
          Token: ${{ secrets.Demo }}
        run: |
          "Token=$env:Token" >> $env:GITHUB_ENV
      - name: Performing Branch creation   
        shell: pwsh
        run: |
          function getcommit_id
          {
           param(
            [string]$Repo_Name
           )
           git clone https://github.com/ramnaveen1099/$Repo_Name.git

           $commit_id= git show --no-patch --no-notes --pretty='%H'
           Write-Host "Commitid: $commit_id"
           return $commit_id
          }

          function create_branch
          {
           param(
           [string]$Repo_Name,
           [string]$Branch_Name,
           [string]$commit_id
           )
           Write-Host "Creating branch name ::$Branch_Name"
           $token = ConvertTo-SecureString $env:Token -AsPlainText -Force
           $Branch_tag=$Branch_Name -split"/"
           $tag=$Branch_tag[0]
           Write-Host $tag

           if($tag -eq 'feature')
           {
             $body = @{
               ref="ref/heads/$Branch_Name"
               sha=$commit_id
             }

           }
           else{
             $body = @{
               ref="refs/heads/$Branch_Name"
               sha=$commit_id
             }
           }

           $Parameters = @{
              Method = "POST"
              Uri =  "https://api.github.com/repos/ramnaveen1099/"+$Repo_Name+"/git/refs"
              Body = ($body | ConvertTo-Json)
              ContentType = "application/json"
              Token= $token
          }
          $response = Invoke-RestMethod @Parameters -Authentication Bearer -SkipHttpErrorCheck -StatusCodeVariable "scv"
          Write-verbose "Response :: $($response | ConvertTo-Json )" -Verbose
          Write-verbose "Creating branch:- $Branch_Name Response Code :: $scv" -Verbose
          
          
          }
          $filePath= 'Branch/Branch_details.csv'
          Write-Host "Input Parameter File Path: $filePath"
          $testPath=Test-Path $filePath
          if($testPath -eq $true){
            Write-Host "Input Parameter File Exist"
            $allCsvData=Import-CSV -Path $filePath
            foreach ($csvData in $allCsvData)  
            {
              Write-Verbose "Branch_Details ::- `n Repo_Name :: $($csvData.Repo_Name), Branch_Name :: $($csvData.Branch_Name)" -Verbose
              $Repo_Name=$($csvData.Repo_Name).trim()
              $Branch_Name=$($csvData.Branch_Name).trim()
              $id= getcommit_id -Repo_Name $Repo_Name
              $branch= create_branch -Repo_Name $Repo_Name -Branch_Name $Branch_Name -commit_id $commit_id
            }
            }

        
